# -*- coding: utf-8 -*-
"""Build final manuscript with v7 effective parameters."""
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
import os

doc = Document()
style = doc.styles['Normal']
style.font.name = 'Times New Roman'
style.font.size = Pt(12)

def h1(t): return doc.add_heading(t, level=1)
def h2(t): return doc.add_heading(t, level=2)
def p(t):
    pp = doc.add_paragraph(t)
    for r in pp.runs: r.font.size=Pt(12); r.font.name='Times New Roman'
    return pp

# ═══ TITLE ═══
tp = doc.add_paragraph(); tp.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = tp.add_run('Coupled Release\u2013Transport Modeling and Tracer Flux Method for Per-Stage Production Allocation from Tracer-Proppant Breakthrough Curves')
r.bold=True; r.font.size=Pt(14)

# ═══ ABSTRACT ═══
h1('Abstract')
p('Tracer proppants enable long-term per-stage production monitoring without downhole hardware, but extracting per-stage contribution rates from wellhead breakthrough curves (BTCs) requires jointly accounting for sustained tracer release from the polymer matrix and transport through the production tubing\u2014a coupled inverse problem not addressed by current practice, which applies the Korsmeyer\u2013Peppas (K\u2011P) model for batch release characterization and the advection\u2013dispersion framework for transport interpretation separately. We develop a coupled release\u2013transport model that decomposes the BTC into a Gaussian pulse (shut-in accumulation slug) and an erfc tail (sustained matrix-diffusion-controlled release), linked by a smooth hyperbolic-tangent transition. The six-parameter model is validated with an oleophilic epoxy/Fe\u2083O\u2084 tracer proppant (ESP\u2011T) in core displacement experiments. The dual-component formulation is statistically decisive over four single-component alternatives (\u0394AICc = 32.7, F-test p < 10\u207b\u2076, R\u00b2 = 0.9939). The fitted flow rate (0.46 mL/min) agrees with the independent pump setting (0.50 mL/min) within 8% without being constrained in the objective function. The Peclet number (Pe = 0.934) independently confirms the non-Fickian transport mechanism identified via K\u2011P kinetics (n = 0.45\u20130.85). The erfc tail accounts for 47% of the integrated signal, a result stable to within \u00b10.8% across a six-fold variation in the transition width. Under two-phase flow, the oil-phase tracer mass flux eliminates water-dilution artifacts and tracks oil production rates (Pearson r = 0.97, RMSD = 8.3%). The framework enables per-interval production allocation from wellhead samples alone, requiring no downhole tools and only a single shut-in.')

h1('Keywords')
p('Tracer proppant; Breakthrough curve; Advection\u2013dispersion equation; Release kinetics; Production allocation; Two-phase flow; Epoxy resin; Tracer flux')

# ═══ 1. INTRODUCTION ═══
h1('1. Introduction')

p('Multi-stage hydraulic fracturing has enabled economic production from unconventional reservoirs, but completion diagnostics remain hindered by a persistent question: how much does each fracture stage produce? Production logging across hundreds of horizontal wells revealed that approximately 30\u201340% of perforation clusters contribute negligibly to production [1], motivating two decades of work on completion optimization and re-stimulation strategies [2,3]. Yet the ability to routinely measure per-stage contribution at the surface has not kept pace. Production logging tools require well intervention via coiled tubing or tractor and capture only a snapshot of the inflow profile [4]. Distributed fiber-optic sensing\u2014both distributed temperature sensing (DTS) and distributed acoustic sensing (DAS)\u2014has enabled real-time monitoring of stimulation operations and qualitative inflow profiling without intervention [5,6], but permanent fiber installation and surface instrumentation remain costly [7]. Microseismic monitoring characterizes stimulated reservoir volume rather than production contribution per stage [3,8]. A method that delivers quantitative per-stage production allocation from surface samples alone\u2014without downhole tools, permanent installation, or repeated well intervention\u2014would fundamentally change completion diagnostics.')

p('Tracer technology offers a pathway toward this method. Since the first documented oilfield tracer test using radioactive iodine in 1954 [9], tracer methods have evolved from qualitative inter-well connectivity assessment to quantitative residual oil saturation measurement via partitioning inter-well tracer tests [10,11] and, more recently, to stage-level inflow profiling in multi-stage fractured wells [12]. Tracer proppants\u2014in which a chemical tracer is immobilized within a solid proppant carrier and co-injected with the proppant pack\u2014offer a key advantage: the tracer remains in the fracture after placement, enabling long-term monitoring from surface samples without repeated injection. A growing body of material designs has been demonstrated: Zhao et al. (2020) used solvent-evaporated dye coatings on ceramic proppants [13]; Zhou et al. (2022) encapsulated carbon quantum dots in polymer-coated ceramics [14]; Li et al. (2023) developed rare-earth-doped polymer coatings for multi-element coding [15]; Gong et al. (2024) synthesized oleophilic Fe\u2083O\u2084/polystyrene microspheres for oil-phase selective release [16]; Ren et al. (2024) prepared multi-colored dye-tracer proppants for quantitative flowback assessment [17]; and Malyavko et al. (2023) demonstrated quantum-dot-encoded polymer microspheres for fluid-phase-resolved inflow profiling [18]. Across these diverse material platforms, a common interpretation gap persists: existing methods can confirm which stages produce, but cannot quantify how much each stage produces from the breakthrough curve alone, because the observed signal is shaped jointly by the unknown tracer release rate and the unknown transport parameters of the production system.')

p('The release side of this coupled problem is addressed by the Korsmeyer\u2013Peppas (K\u2011P) power-law model. Originally developed for drug delivery systems [19,20] and extended to coupling of diffusion and polymer relaxation [21], the K\u2011P model C/C\u2080 = K\u00b7t\u207f identifies the release mechanism through the diffusional exponent n and provides the temperature-dependent rate constant K. This framework has been productively applied to characterize release from diverse tracer-proppant systems including rare-earth-doped polymer coatings [15], polystyrene-encapsulated Fe\u2083O\u2084 nanoparticles [16], epoxy-matrix sustained-release tracers [22], and nano-Fe\u2083O\u2084 tracers in copolymer matrices [23]. However, K\u2011P is fundamentally a zero-dimensional batch description: it characterizes release into a well-mixed vessel with no spatial coordinate, no flow field, and no pathway from a release rate to a concentration measured at a distant sampling point. Alone, it cannot predict the wellhead concentration\u2014the quantity that encodes production information.')

p('On the transport side, the one-dimensional advection\u2013dispersion equation (ADE) provides a mature analytical framework for interpreting breakthrough curves. Van Genuchten and Alves (1982) compiled analytical solutions covering a wide range of boundary and initial conditions [24]; the temporal moments of a BTC yield the mean residence time and dispersivity. Full-curve ADE inversion has been applied to determine reservoir properties from inter-well tracer tests [25], to interpret physical mechanisms in partitioning tracer tests [26], to model chemical tracer transport under two-phase flow via analytical solutions [27], and to describe tracer transfer in multi-stage fractured wells [28]. A comprehensive review of tracer testing techniques [29] confirms that ADE-based interpretation remains the standard approach across the petroleum industry. The common premise across these applications, however, is that the tracer source term is known\u2014an injection pulse of specified mass, duration, and location. A tracer-proppant BTC violates this premise: the source is not a single operator-controlled injection but a sustained, matrix-diffusion-controlled release. No existing framework couples the sustained release source term to the ADE transport solution.')

p('In this work, we close this gap by coupling the release source term to the ADE transport solution. We construct a piecewise release\u2013transport model that decomposes the BTC into two physically motivated components: a Gaussian pulse (shut-in accumulation slug) and an erfc tail (sustained matrix-diffusion-controlled release), linked by a C\u00b9-continuous hyperbolic-tangent transition. Six parameters are estimated simultaneously from a single BTC by nonlinear least squares. The model is validated through a predictive self-calibration test: the flow rate Q is left entirely unconstrained in the objective function; the model must recover the independently set pump flow rate from the BTC shape alone. Applied to an oleophilic epoxy/Fe\u2083O\u2084 tracer proppant (ESP\u2011T) in core displacement experiments, the model recovers Q = 0.46 mL/min against the pump setting of 0.50 mL/min\u2014a deviation of 8%. Epoxy resins offer high mechanical strength, thermal stability, and chemical resistance compared to thermoplastic alternatives [30\u201332], and their ability to sustain controlled tracer release has been demonstrated in both water-soluble [22] and oil-soluble configurations [33]. The Peclet number (Pe = 0.934) independently corroborates the non-Fickian transport mechanism identified from static K\u2011P batch kinetics (n = 0.45\u20130.85)\u2014two completely separate experiments converging on the same dispersion-dominated transport picture. We then introduce a tracer flux method for production allocation under two-phase flow: the oil-phase tracer mass flux F_O = C_oil \u00d7 Q_oil is invariant with total flow rate at a given oil\u2013water ratio (Pearson r = 0.97, RMSD = 8.3%), eliminating the dilution artifact. By doping each fracture stage with a distinct tracer element, per-stage contribution rates are obtained as (F_O,i / C_i) / \u03a3(F_O,j / C_j) from periodic ICP\u2011MS wellhead samples alone. We validate the complete framework in single-phase and two-phase core displacement experiments, and outline the pathway to multi-stage field deployment.')

# ═══ 2. EXPERIMENTAL ═══
h1('2. Experimental')

h2('2.1 Materials')
p('Analytical grade reagents\u2014including FeCl\u2083 (\u226599.0%), FeCl\u2082\u00b74H\u2082O (\u226599.0%), MnCl\u2082\u00b76H\u2082O (\u226599.0%), stearic acid (\u226599.5%), and anhydrous ethanol\u2014were purchased from Chengdu Kelong Chemical Co., Ltd. Industrial grade materials included guar gum, E51 epoxy resin (epoxy value 0.48\u20130.54 mol/100 g, Nantong Xingchen Synthetic Materials), T31 curing agent (phenolic amine, \u226595% effective component), and hollow glass microspheres (\u226599% purity). Dodecane (\u226599%, Chengdu Kelong) served as the model oil phase. All reagents were used as received. Detailed specifications are provided in Table S1 (Supplementary Material).')

h2('2.2 ESP\u2011T Synthesis')
p('ESP\u2011T was synthesized in three steps. (i) Stearic acid-modified nano-Fe\u2083O\u2084 (nano-Fe\u2083O\u2084@SA) was prepared by co-precipitation: 2.703 g FeCl\u2083 and 1.15 g FeCl\u2082\u00b74H\u2082O in 100 mL deionized water at 80 \u00b0C under N\u2082, doped with 2 \u00d7 10\u207b\u2075 mol MnCl\u2082\u00b76H\u2082O; 5.5 mL NH\u2083\u00b7H\u2082O was added, and the reaction proceeded at pH 10 for 2 h. The black precipitate was magnetically separated, washed to neutrality, and sonicated with ethanolic stearic acid for oleophilic surface modification. (ii) A pre-mixture of 20 mL E51 epoxy resin, ~0.75 g nano-Fe\u2083O\u2084@SA (~3.3 wt% of the final formulation), 1 g hollow glass microspheres, and 7 g T31 curing agent was homogenized. (iii) The pre-mixture was emulsified in a SiO\u2082/guar gum aqueous dispersion and cured at 50 \u00b0C for 1 h, then rinsed and dried at 80 \u00b0C for 10 h. Pure epoxy microspheres were prepared identically without nano-Fe\u2083O\u2084@SA as a reference. The co-precipitation method accommodates other transition metals (Zn, Cu, Co, Ni) and rare earth elements (Eu, Dy, Nd) for multi-stage tracer coding.')

h2('2.3 Characterization')
p('Microstructure and elemental distribution were characterized by scanning electron microscopy with energy-dispersive X-ray spectroscopy (SEM\u2011EDS, ZEISS Sigma 500) and optical microscopy (Leica DM2700P). Thermal stability was evaluated by thermogravimetric analysis and differential scanning calorimetry (TGA/DSC, TA Instruments Q500, air atmosphere, 10 \u00b0C/min, 50\u2013800 \u00b0C). Water contact angle (WCA) was measured using a video optical contact angle analyzer (OCA20, 5 \u03bcL droplets, n = 5). Physical and mechanical properties\u2014including bulk density, apparent density, sphericity, roundness, acid solubility (HCl 12 wt%/HF 3 wt%, 65 \u00b0C, 30 min), and crush rate (52 MPa, 2 min)\u2014were evaluated per SY/T 5107\u20132016. Oil-water transport selectivity was assessed via packed-bed filtration time (2.0 g proppant, 20 mL fluid, 200-mesh screen). Detailed protocols are provided in the Supplementary Material (Section S2).')

h2('2.4 Batch Release Kinetics')
p('ESP\u2011T (5 g, 40\u201370 mesh) was immersed in 100 mL dodecane in sealed glass vials placed in thermostatic oil baths at 30, 60, 90, and 120 \u00b0C. Sampling was conducted at 12 h intervals over 14 days; tracer metal ion concentration was quantified by inductively coupled plasma mass spectrometry (ICP\u2011MS, PerkinElmer NexION 300X). Release data within M_t/M_\u221e < 0.6\u2014the range in which the Korsmeyer\u2013Peppas power law C/C\u2080 = K\u00b7t\u207f is valid\u2014were fitted to determine the kinetic parameters K and n.')

h2('2.5 Core Displacement Experiments')
p('A dynamic displacement apparatus was used to simulate single-interval production. A steel core was packed with ESP\u2011T, sealed with 200-mesh screens, and placed in a core holder under 5 MPa confining pressure. The production tubing connecting the core outlet to the sampling point was 1 m in length with an inner diameter of 1 mm. For single-phase experiments, the system was saturated with dodecane at 5 mL/min, shut in for 96 h to allow tracer accumulation, then displaced at a pump setting of 0.50 mL/min. The pump setting serves as the independent flow-rate reference for model validation (Section 4.3). Effluent was sampled at 4-min intervals (2 mL per sample, 21 samples) and analyzed by ICP\u2011MS to construct the BTC. For two-phase experiments, dodecane and deionized water were co-injected at three oil-water volume ratios (OWR = 4:1, 1:1, 1:4) and four total flow rates (0.1\u20130.4 mL/min) under steady-state flow. Sampling was conducted at 5-min intervals; both the OWR and tracer concentration were recorded.')

# ═══ 3. MODEL DEVELOPMENT ═══
h1('3. Model Development')

h2('3.1 Physical Basis')
p('The core displacement protocol imposes a tracer history that any quantitative interpretation must respect. During the 96-h shut-in, tracer continuously diffuses from the epoxy matrix into the proppant pack and the near-wellbore region (Source I: shut-in accumulation slug). When flow resumes, this accumulated tracer is swept toward the sampling point as a coherent slug. Simultaneously, the polymer matrix continues to release tracer after flow resumes\u2014the model oil continually contacts the proppant surface, swelling progresses, and tracer diffuses through the gel layer into the flowing stream (Source II: sustained matrix-diffusion-controlled release). These two sources are physically irreducible\u2014they are consequences of the experimental shut-in, not modeling choices.')

h2('3.2 Governing Equations')
p('Tracer transport is governed by the one-dimensional ADE, \u2202C/\u2202t + v\u00b7\u2202C/\u2202x = D\u00b7\u2202\u00b2C/\u2202x\u00b2, where v is the cross-section-averaged flow velocity and D = \u03b1\u00b7v is the longitudinal dispersion coefficient (\u03b1 = dispersivity). The model employs effective transport parameters that describe the combined response of the core, proppant pack, and production tubing. For an instantaneous pulse injection, the classical solution is C(x,t) = (M/A_cross)\u00b7(1/\u221a(4\u03c0Dt))\u00b7exp(\u2212(x \u2212 vt)\u00b2/(4Dt)). Substituting the tube-flow relations yields the dimensionless working variable z = (x\u03c0d\u00b2 \u2212 4Qt) / \u221a(16\u03b1Qt\u03c0d\u00b2), where x and d are effective length and diameter scales, not literal tubing dimensions. Source I enters as the Gaussian rise component C_rise(t) = c_b + (A\u00b7d)/\u221a(16\u03c0\u03b1Qt\u00b7d\u00b2) \u00d7 exp(\u2212z\u00b2). Source II enters as the erfc fall component C_fall(t) = c_b + (a/2) \u00d7 erfc(\u2212z). The two components are blended through a C\u00b9-continuous hyperbolic-tangent weight function w(t) = \u00bd[1 + tanh((t\u2080 \u2212 t)/\u03c3)], yielding the full model: C(t) = c_b + w(t)\u00b7C_rise(t) + [1 \u2212 w(t)]\u00b7C_fall(t).')

h2('3.3 Parameter Estimation and Model Selection')
p('Equation (1) contains seven fitted coefficients: baseline c_b, pulse amplitude A, tail amplitude a, dispersivity \u03b1, effective flow rate Q, crossover time t\u2080, and transition width \u03c3. Derived transport properties are Pe = x/\u03b1, v = 4Q/(\u03c0d\u00b2), and MRT = x/v. The inverse problem\u2014extracting transport and release parameters from a single BTC\u2014was solved by a two-pass estimation strategy: global basin location via differential evolution (four independent seeds, wide parameter bounds) followed by gradient-based local refinement. Q was bounded to [10, 5000] in model units (corresponding to a wide effective range) with no penalty, prior, or constraint directing the search toward the pump value. The identical protocol was applied to all five candidate models to ensure fair comparison. Full optimization details are provided in the Supplementary Material (Section S5.3).')

# ═══ 4. RESULTS AND DISCUSSION ═══
h1('4. Results and Discussion')

h2('4.1 ESP\u2011T Characterization')
p('SEM micrographs confirm that ESP\u2011T microspheres exhibit excellent sphericity (>0.9) with no inter-particle agglomeration. Elemental mapping confirms Fe distributed throughout the particle cross-section, consistent with bulk encapsulation. TGA/DSC identifies the primary epoxy decomposition at 357 \u00b0C (DTG peak), far exceeding typical downhole temperatures (80\u2013200 \u00b0C). Stearic acid modification increases the water contact angle from 72.3\u00b0 (pure epoxy) to 104.6\u00b0 (ESP\u2011T, hydrophobic). ESP\u2011T exhibits a bulk density of 0.646 g/cm\u00b3 (<1.0 g/cm\u00b3, enabling self-suspension), acid solubility of 3.3% (<5% per SY/T 5107\u20132016), and a crush rate of 2.9% at 52 MPa. The water/oil passage time ratio of 5.53 quantitatively confirms the oleophilic surface character.')

h2('4.2 Temperature-Dependent Tracer Release Kinetics')
p('Tracer release from ESP\u2011T in dodecane was measured at 30, 60, 90, and 120 \u00b0C. Release accelerates with temperature throughout the 14-day measurement period. The K\u2011P model was fitted within its validated range (M_t/M_\u221e < 0.6; Table 2). The rate constant K increases systematically from 0.0554 (30 \u00b0C) to 0.1964 (120 \u00b0C), and all n values fall within 0.45\u20130.85 (R\u00b2 > 0.94 at every temperature), corresponding to anomalous (non-Fickian) transport co-governed by Fickian diffusion and Case-II polymer relaxation. The physical picture is one of solvent-driven swelling: dodecane permeates the cross-linked epoxy network, generating an inner glassy core and an outer gel layer; swelling expands transport channels through which doped metal ions diffuse into the external medium.')

h2('4.3 BTC Decomposition and Model Validation')
p('Table 3 compares the dual-component model against four single-component alternatives fitted to the same BTC dataset using the identical protocol. The dual-component model achieves R\u00b2 = 0.9939 (RMSE = 0.0210), decisively outperforming the single Gaussian (R\u00b2 = 0.9482, \u0394AICc = 32.7), single erfc (R\u00b2 = 0.7159, \u0394AICc = 68.4), exponential decay (R\u00b2 = 0.7517, \u0394AICc = 62.5), and K\u2011P power law (R\u00b2 = \u22120.0193, \u0394AICc = 92.2). An F-test decisively rejects the simpler single-Gaussian model (F(3, 14) = 34.70, p < 10\u207b\u2076). This evidence is necessary but not sufficient: \u0394AICc eliminates the single-process alternatives, but cannot by itself establish that the dual-component structure is physically correct.')

p('The decisive test of physical validity is the recovery of the independently known pump flow rate. The model was fitted with Q unconstrained in the objective function; the optimizer was free to assign Q any value within wide effective bounds. It consistently converged to 0.46 mL/min across four independent global searches, against the pump setting of 0.50 mL/min\u2014a deviation of 8% (Fig. 1c). An incorrect model structure could have achieved comparable R\u00b2 with an arbitrary Q by compensating with other parameters. The fact that Q emerges at 0.46 mL/min, entirely unforced, constitutes evidence that the model structure captures the actual transport physics.')

p('Separating the fitted curve into its two components (Fig. 1a) reveals that the Gaussian pulse accounts for 53% and the erfc tail 47% of the integrated tracer signal over the 105-min measurement window. The fitted crossover time t\u2080 = 25.66 min marks the transition from pulse-dominated to tail-dominated behavior, with \u03c3 = 3.96 min approximately equal to the 4-min sampling interval.')

p('The Peclet number derived from the fit, Pe = x/\u03b1 = 0.934 \u2248 1, indicates that convection and dispersion contribute approximately equally to tracer transport\u2014a signature of non-piston, dispersion-influenced displacement. This result is independently corroborated by the K\u2011P kinetic analysis (Section 4.2), which identifies the tracer release mechanism as anomalous (non-Fickian) transport with n = 0.45\u20130.85 across all four temperatures. These two findings emerge from completely separate experiments: the K\u2011P analysis from static batch release in glass vials, and the Pe from dynamic core-flood BTC fitting. Their convergence on the same physical picture\u2014that tracer transport is governed by coupled diffusion and advection, with neither mechanism dominant\u2014provides strong, independent evidence that both the release characterization and the transport model are physically sound.')

h2('4.4 Signal Decomposition Robustness')
p('To verify that the 47% erfc tail contribution is not an artifact of the chosen transition width, \u03c3 was varied from 1.98 to 11.89 min (a six-fold range, 0.5\u00d7\u20133.0\u00d7 the fitted value) while holding the other six parameters fixed. The erfc tail contribution varies by less than one percentage point across the entire scan range (46.8\u201347.5%), confirming that the decomposition is a robust structural feature of the BTC rather than a parametrically tuned outcome.')

h2('4.5 Two-Phase Production Allocation via Tracer Flux')
p('Under steady-state two-phase flow, the tracer concentration C_oil measured at the outlet decreases with increasing total flow rate Q_total\u2014a consequence of dilution. Concentration alone is therefore a poor proxy for the production rate. We resolve this by working with the oil-phase tracer mass flux F_O = C_oil \u00d7 Q_oil. At steady state, F_O equals the release rate from the ESP\u2011T pack and is independent of Q_total\u2014it reflects only what the proppant releases, governed by the oil-wetted surface area. This is confirmed experimentally: at each OWR, F_O remains approximately constant across the full range of total flow rates (0.1\u20130.4 mL/min). Normalizing by the single-phase reference flux F_O,ref = 3.187 \u00b1 0.15 \u03bcg/min (triplicate), the normalized flux tracks the independently known oil flow rate across all three OWR conditions (Pearson r = 0.97, RMSD = 8.3%).')

# ═══ 5. FIELD IMPLICATIONS ═══
h1('5. Implications for Field-Scale Deployment')
p('The coupled framework\u2014K\u2011P kinetics \u2192 ADE model \u2192 tracer flux method\u2014provides a complete pathway from wellhead concentration measurements to per-stage production allocation. For a multi-stage well, each fracture stage is assigned a distinct tracer element (e.g., Mn, Zn, Cu, Eu, Dy) doped into the ESP\u2011T matrix. After a single shut-in, produced fluid is sampled at the wellhead and analyzed by ICP\u2011MS to obtain the concentration C_i of each tracer element. During flowback, the full BTC of each element is recorded; the ADE model decomposes each BTC into its shut-in slug and sustained-release components and provides the Peclet number for transport regime diagnosis. During steady production, periodic sampling yields the steady-state concentration C_i,ss. The per-stage contribution rate is: Contribution_i = (F_O,i / C_i) / \u03a3(F_O,j / C_j), where F_O,i is the calibrated tracer flux for stage i, obtained from laboratory reference measurements scaled by the proppant mass and reservoir temperature using the K\u2011P-derived temperature dependence.')
p('Several limitations define the path from laboratory demonstration to field deployment. The framework has been validated on a single interval at laboratory scale; multi-interval configurations remain untested. All experiments used dodecane as the model oil; crude oil introduces additional complexity. The chemical stability of the epoxy matrix in aggressive downhole environments (H\u2082S, CO\u2082, high-salinity brines, >120 \u00b0C) has not been evaluated. The flux calibration is based on three OWR levels; a larger matrix would strengthen the calibration. Batch-specific F_O,ref determination is advisable for field deployment.')

# ═══ 6. CONCLUSIONS ═══
h1('6. Conclusions')
for c in [
    'A coupled release\u2013transport model was developed that decomposes a tracer-proppant breakthrough curve into a Gaussian pulse (shut-in accumulation slug) and an erfc tail (sustained matrix-diffusion-controlled release), linked by a C\u00b9-continuous hyperbolic-tangent transition. The dual-component structure is statistically decisive over four single-process alternatives (\u0394AICc = 32.7, F-test p < 10\u207b\u2076, R\u00b2 = 0.9939).',
    'The model recovers the independently set pump flow rate (0.50 mL/min) as 0.46 mL/min\u2014a deviation of 8%\u2014with Q unconstrained in the objective function, demonstrating that the model structure captures the actual transport physics rather than merely fitting the curve.',
    'The Peclet number (Pe = 0.934 \u2248 1) independently corroborates the non-Fickian transport mechanism (n = 0.45\u20130.85) identified from static K\u2011P batch kinetics\u2014two completely separate experiments converging on the same dispersion-influenced transport picture.',
    'The erfc tail accounts for approximately 47% of the integrated tracer signal, stable to within \u00b10.8 percentage points across a six-fold variation in the transition width, confirming that sustained matrix-diffusion-controlled release contributes nearly half of the total detected tracer.',
    'A tracer flux method enables production allocation under two-phase flow: F_O = C_oil \u00d7 Q_oil is invariant with total flow rate at a given oil\u2013water ratio (r = 0.97, RMSD = 8.3%). For multi-stage wells, per-stage contribution rates are obtained as (F_O,i / C_i) / \u03a3(F_O,j / C_j) from periodic wellhead ICP\u2011MS samples, requiring no downhole tools and only a single shut-in.',
]:
    p(c)

# ═══ SAVE ═══
BASE = r'c:\Users\郝\Desktop\claude\四氧化三铁环氧树脂拟合\ESP-T_投稿文件'
out = os.path.join(BASE, 'ESP-T_v7_manuscript.docx')
doc.save(out)
print(f'Saved: {out}')
print(f'Paragraphs: {len(doc.paragraphs)}')
