# -*- coding: utf-8 -*-
"""Check equations, simplify derivation to minimum, fix paragraph text."""
from docx import Document

SRC = r'c:\Users\郝\Desktop\claude\四氧化三铁环氧树脂拟合\Fabrication and Performance of ESP.docx'
DST = r'c:\Users\郝\Desktop\claude\四氧化三铁环氧树脂拟合\ESP_final_v2.docx'

doc = Document(SRC)

def set_para_text(para, text):
    for run in para.runs:
        run.text = ''
    if para.runs:
        para.runs[0].text = text
    else:
        para.add_run(text)

# ===== PARA 146 (empty after intro): insert derivation =====
set_para_text(doc.paragraphs[146],
    "The model is based on the one-dimensional advection-dispersion equation "
    "∂C/∂t + v·∂C/∂x = D·∂²C/∂x², where v = 4Q/(πd²) and D = αv. "
    "For the tracer pulse released from ESP-T during the shut-in period, "
    "the analytical solution of the ADE for an instantaneous slug injection "
    "gives the Gaussian-form rising component in Eq. (6). For the sustained "
    "slow release after the main pulse, solving the ADE with a continuous-source "
    "boundary condition yields the erfc tailing component. A tanh weighting "
    "function smoothly blends the two solutions at t₀, producing a physically "
    "continuous breakthrough curve.")

# ===== PARA 147: transition sentence to equation =====
set_para_text(doc.paragraphs[147],
    "Accordingly, the tracer breakthrough curve was fitted using the following "
    "piecewise advection-dispersion model with smooth transition:")

# ===== PARA 148: check equation text (embedded object, check if placeholder needed) =====
# This para contains embedded equation — leave as-is

# ===== PARA 149 =====
set_para_text(doc.paragraphs[149], "where:")

# ===== PARAS 150-156: variable list =====
new_vars = [
    "c_b = baseline concentration after the tracer signal has stabilized;",
    "A = peak amplitude coefficient, proportional to the tracer mass accumulated in the oil phase during the shut-in period;",
    "a = tailing amplitude coefficient, proportional to the sustained tracer release rate from the ESP-T matrix;",
    "α = dispersivity, characterizing the axial spreading of the tracer slug along the flow line, cm;",
    "Q = effective volumetric flow rate through the flow line, cm³/min;",
    "t₀ = time at which sustained matrix-diffusion release overtakes the initial pulse as the dominant signal source, min;",
    "σ = time span of the transition from pulse-dominated to tailing-dominated regime, min.",
]
# Add x and d as a note after the variables
set_para_text(doc.paragraphs[157],
    "In the above expressions, x = 100 cm and d = 5 cm are the fixed length "
    "and inner diameter of the flow line, respectively. "
    "In Eq. (6), the rising component C_rise captures the advective-dispersive "
    "arrival of the tracer slug at the sampling point, while the tailing component "
    "C_fall describes the slow, sustained release of residual nano-Fe₃O₄@SA from "
    "the epoxy matrix into the flowing oil. The parameter t₀ marks the time at which "
    "the tailing component begins to dominate the signal, and σ controls how rapidly "
    "this transition occurs. This two-component structure reflects the physical "
    "reality that the tracer signal recorded at the sampling point originates from "
    "two superimposed processes: a short-duration concentration pulse generated by "
    "tracer accumulation during shut-in, and a prolonged tail governed by the "
    "matrix-diffusion-controlled release kinetics established in Section 3.10.")
for para_idx, text in zip(range(150, 157), new_vars):
    set_para_text(doc.paragraphs[para_idx], text)

# ===== PARA 157: model description (now moved to 146, keep this brief) =====
set_para_text(doc.paragraphs[157],
    "In Eq. (6), the rising component C_rise captures the advective-dispersive "
    "arrival of the tracer slug at the sampling point, while the tailing component "
    "C_fall describes the slow, sustained release of residual nano-Fe₃O₄@SA from "
    "the epoxy matrix into the flowing oil. The parameter t₀ marks the center of "
    "the transition between these two regimes, and σ controls its width. This "
    "two-component structure reflects the physical reality that the tracer signal "
    "recorded at the sampling point originates from two superimposed processes: "
    "a short-duration pulse generated by tracer accumulation during shut-in, and "
    "a prolonged tail governed by the matrix-diffusion-controlled release kinetics "
    "established in Section 3.10.")

# ===== PARA 159: results =====
set_para_text(doc.paragraphs[159],
    "Fitting of Eq. (6) to the experimental data (Figure 3-9b) yields "
    "R² = 0.9939 and RMSE = 0.0210. The fitted parameters and derived transport "
    "properties are listed in Table 3-3. Key results include: mean flow velocity "
    "v = 4Q/(πd²) = 2.59 cm/min; dispersivity α = 107.1 cm; Péclet number "
    "Pe = x/α = 0.934. The Pe < 1 indicates dispersion-dominated transport "
    "along the flow line, consistent with the gradual, sustained release of "
    "nano-Fe₃O₄@SA from the ESP-T matrix. A comparison between the fitted "
    "flow rate (0.46 mL/min) and the experimental pump-set flow rate "
    "(0.5 mL/min) is shown in Figure 3-9(c), yielding a relative error of 8%, "
    "which verifies the accuracy of the model for flow rate determination from "
    "tracer breakthrough data. The mean residence time MRT = 37.4 min agrees "
    "well with the convective travel time x/v = 38.6 min (ratio 0.967). "
    "Deconvolution shows that 47% of the total tracer signal originates "
    "from the erfc tailing component, confirming the significant contribution "
    "of matrix-diffusion-controlled release to the overall monitoring signal "
    "and its consistency with the non-Fickian mechanism identified in "
    "Section 3.10.")

# ===== Save =====
doc.save(DST)
print(f"Saved: {DST}")
print("Derivation: 3 sentences. Total modification: 8 paragraphs.")