# -*- coding: utf-8 -*-
"""SCI journal polish — fix all identified issues."""
from docx import Document
from docx.oxml.ns import qn
import re

SRC = r'c:\Users\郝\Desktop\claude\四氧化三铁环氧树脂拟合\ESP_final_v4.docx'
DST = r'c:\Users\郝\Desktop\claude\四氧化三铁环氧树脂拟合\ESP_final_v5.docx'
doc = Document(SRC)

IMG = set()
for i, p in enumerate(doc.paragraphs):
    for run in p.runs:
        if (run._element.findall('.//'+qn('w:drawing')) or
            run._element.findall('.//'+qn('a:blip'))):
            IMG.add(i); break

def sp(idx, text):
    if idx in IMG: return
    p = doc.paragraphs[idx]
    for r in p.runs: r.text = ''
    if p.runs: p.runs[0].text = text
    else: p.add_run(text)

def clear(idx):
    if idx in IMG: return
    p = doc.paragraphs[idx]
    for r in p.runs: r.text = ''

# ===== 1. REMOVE DUPLICATE methods [51], [56] (old long versions) =====
clear(51)  # old 256-word single-phase methods
clear(56)  # old 206-word two-phase methods

# ===== 2. REMOVE orphan "2.6 Oil Production Monitoring Experiments" text [54] =====
clear(54)

# ===== 3. FIX duplicate conclusions =====
# [169] old synthesis, [171] old properties → clear them
# Keep [173] new synthesis, [175] new tracer, [177] summary
clear(169)
clear(171)

# ===== 4. FIX figure references in body text =====
# Figure 3-4 → Figure 3-2 (TGA), Figure 3-5 → Figure 3-3 (WCA)
# Figure 3-6 → Figure 3-4 (Density), etc.
fig_map = {
    'Figure 3-4': 'Figure 3-2', 'Figure 3-5': 'Figure 3-3',
    'Figure 3-6': 'Figure 3-4',
}
for para in doc.paragraphs:
    for run in para.runs:
        if run.text:
            for old, new in fig_map.items():
                if old in run.text:
                    run.text = run.text.replace(old, new)

# ===== 5. FIX figure caption text =====
# [91] "Figure 3 - 4 TGA/DTG..." → "Figure 3-2"
sp(91, "Figure 3-2 TGA/DTG and DSC curves of Fe3O4@epoxy resin proppant")
# [98] "Figure 3 - 5 (a) WCA..." → "Figure 3-3"
sp(98, "Figure 3-3 (a) WCA of epoxy resin patch (b) WCA of patch after doping with nano-Fe3O4@SA")
# [108] "Figure 3 - 6 Bulk density..." → "Figure 3-4"
sp(108, "Figure 3-4 Bulk density and apparent density of epoxy microspheres and ESP-T")

# ===== 6. SPLIT overloaded paragraphs =====
# [124] 179 words → split into 2
sp(124,
    "In field applications, formation temperature rises with increasing reservoir "
    "depth, influencing ESP-T expansion and tracer release behavior. The release "
    "profiles of ESP-T at various temperatures are presented in Figure 3-6(a), where "
    "C/C0 represents the normalized concentration, C denotes the tracer concentration "
    "at a specific time, and C0 is the maximum release concentration. As shown, the "
    "relative release concentration increases over time and with rising temperature, "
    "demonstrating that elevated temperature accelerates tracer release. Figure 3-6(c) "
    "further shows that the release rate is high during initial fluid contact, then "
    "gradually slows and stabilizes. Cumulative tracer release at 120 C over 14 days "
    "remains detectable by ICP-MS, confirming long-term monitoring suitability. "
    "To elucidate the release mechanism, the Korsmeyer-Peppas (K-P) model was fitted "
    "to the release curves at each temperature. The K-P model is defined by Eq. (5):")

# [139] 196 words → keep first half, move second half
sp(139,
    "To characterize the tracer production curve, a well shut-in phase was incorporated "
    "to achieve concentrated tracer release. Continuous sampling was employed with a "
    "sample volume of 2 mL, a wellhead flow rate of 0.5 mL/min, and a sampling interval "
    "of 4 min; the tracer concentration peak arrives at 20-25 min due to the sample "
    "volume effect. Figure 3-7(a) presents the normalized tracer production profile. "
    "The tracer concentration exhibits an initial rapid rise followed by a gradual "
    "decline, with a distinct peak corresponding to the high-concentration tracer "
    "solution generated by ESP-T during shut-in. This observation is consistent with "
    "the findings in Section 3.6: ESP-T realizes synergistic tracer release via Fickian "
    "diffusion and Case-II relaxation, enabling sustained tracer signals under flow.")

# ===== 7. POLISH key paragraphs =====
# [157] Results — split long sentence
sp(157,
    "The fitted curve is shown in Figure 3-7(b), and the fitted parameters with derived "
    "transport properties are listed in Table 3-3. The model yields R^2 = 0.9939 and "
    "RMSE = 0.0210, with residuals randomly distributed within +/- 2 RMSE. Key derived "
    "parameters are: mean flow velocity v = 2.59 cm/min; longitudinal dispersivity "
    "alpha = 107.1 cm; and Peclet number Pe = 0.934 (Pe < 1, dispersion-dominated "
    "transport). The fitted flow rate (0.46 mL/min) agrees closely with the pump-set "
    "rate (0.5 mL/min; relative error 8%; Figure 3-7c), validating the model accuracy. "
    "The mean residence time (MRT = 37.4 min) matches the convective travel time "
    "(x/v = 38.6 min; ratio 0.967). Deconvolution shows that 47% of the integrated "
    "signal originates from the erfc tailing component, confirming the dominant "
    "contribution of matrix-diffusion-controlled release, consistent with the "
    "non-Fickian mechanism identified in Section 3.6.")

# ===== 8. CLEAN empty paragraphs in conclusions area =====
# [168] is heading, [169] cleared, [170] empty, [171] cleared, [172] empty, [173] new
# Clean up empties
for i in [170, 172, 174, 176, 178]:
    t = doc.paragraphs[i].text.strip()
    if not t:
        clear(i)

# ===== SAVE =====
doc.save(DST)
print(f"SCI polish complete. Saved: {DST}")
print("Fixes: removed duplicate methods/conclusions, renumbered figures,")
print("split long paragraphs, cleaned empty paras.")