# -*- coding: utf-8 -*-
"""
Task 2: Write Section 2 — The Coupled Release-Transport Model
into ESP-T_v2_manuscript.docx (skeleton produced by Task 1).

Writes content into the blank paragraph that follows each Section 2 heading:
  - lead-in paragraph after H1
  - 2.1 Physical Basis
  - 2.2 Governing Equations (7 display equations, centered)
  - 2.3 Parameter Set and Derived Quantities (+ real Word Table 1)
  - 2.4 Validation Strategy: Self-Calibration as Decisive Test

Conventions:
  - '_xyz' in content strings renders as a Word subscript run (c_b -> cb,
    C_rise -> Crise, t_0 -> t0), matching source-document extracted text.
  - Display equations are centered Normal paragraphs of Unicode math,
    consistent with the source manuscripts (which use no OMML).
  - The [Fig. 1] marker paragraph in 2.1 is left untouched (replaced later).
"""
import re
import sys

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH

DOCX = r"C:\Users\郝\Desktop\claude\四氧化三铁环氧树脂拟合\ESP-T_投稿文件\ESP-T_v2_manuscript.docx"

SUB_RE = re.compile(r"_([A-Za-z0-9]+)")


def add_runs(para, text, bold=False, italic=False):
    """Add runs to *para*; '_xyz' segments become subscript runs."""
    pos = 0
    for m in SUB_RE.finditer(text):
        if m.start() > pos:
            r = para.add_run(text[pos:m.start()])
            r.bold = bold
            r.italic = italic
        r = para.add_run(m.group(1))
        r.font.subscript = True
        r.bold = bold
        r.italic = italic
        pos = m.end()
    if pos < len(text):
        r = para.add_run(text[pos:])
        r.bold = bold
        r.italic = italic


def write_into(para, text):
    """Write *text* into an existing (blank) paragraph."""
    add_runs(para, text)
    return para


def insert_before(anchor, text, center=False):
    """Insert a new paragraph immediately before *anchor*; return it."""
    p = anchor.insert_paragraph_before()
    if center:
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    add_runs(p, text)
    return p


def main():
    doc = Document(DOCX)
    paras = doc.paragraphs

    # Idempotency guard: refuse to run twice on the same document.
    if any("This section develops the coupled release–transport model" in p.text
           for p in paras):
        raise SystemExit("Section 2 already written; refusing to duplicate content. "
                         "Restore the skeleton from git first (git checkout -- <docx>).")

    def find_heading(text):
        for i, p in enumerate(paras):
            if p.text.strip() == text:
                return i
        raise SystemExit(f"heading not found: {text!r}")

    i_h1 = find_heading("2. Coupled Release–Transport Model")
    i_21 = find_heading("2.1 Physical Basis")
    i_22 = find_heading("2.2 Governing Equations")
    i_23 = find_heading("2.3 Parameter Set and Derived Quantities")
    i_24 = find_heading("2.4 Validation Strategy: Self-Calibration as Decisive Test")
    i_3 = find_heading("3. Experimental Methods")

    # --- Lead-in after Section 2 heading -----------------------------------
    write_into(paras[i_h1 + 1], (
        "This section develops the coupled release–transport model that underpins the "
        "interpretation of every breakthrough curve (BTC) in this work. The model "
        "decomposes a tracer-proppant BTC into two physically distinct components — a "
        "Gaussian pulse generated by shut-in accumulation and an erfc tail generated by "
        "sustained matrix-diffusion-controlled release — linked by a C¹-continuous "
        "hyperbolic-tangent transition. All model parameters are defined here; "
        "Sections 4.1–4.5 subject the model to statistical selection, physical "
        "self-calibration, and robustness testing."
    ))

    # --- 2.1 Physical Basis -------------------------------------------------
    anchor_21 = paras[i_21 + 2]  # the [Fig. 1] marker paragraph
    write_into(paras[i_21 + 1], (
        "The core displacement protocol imposes a tracer history that any quantitative "
        "interpretation must respect (Fig. 1). During the 96-h shut-in that precedes "
        "flowback (Section 3.4), the pore fluid is static and the proppant pack remains "
        "fully wetted. Tracer continues to diffuse out of the epoxy matrix throughout "
        "this period, and because no fluid movement removes it, the released mass "
        "accumulates in the pore space of the pack and in the adjacent near-wellbore "
        "region. When displacement resumes at the pump rate, this accumulated mass is "
        "swept toward the sampling point as a coherent slug: the outlet concentration "
        "rises steeply and passes through a sharp maximum as the slug is produced. This "
        "is Source I, the shut-in accumulation slug, and it produces the Gaussian-shaped "
        "pulse that dominates the early breakthrough curve."
    ))
    insert_before(anchor_21, (
        "Source II arises from the same shut-in but persists far longer. The polymer "
        "matrix does not stop releasing tracer when flow resumes: the model oil "
        "continues to swell the cross-linked epoxy network, and tracer ions continue to "
        "diffuse from the matrix into the flowing fluid. This sustained, "
        "diffusion-controlled release feeds a low-amplitude concentration tail that "
        "decays slowly and remains measurable long after the main slug has passed the "
        "sampling point."
    ))
    insert_before(anchor_21, (
        "The two sources are physically irreducible — they are not modeling choices but "
        "consequences of the experimental shut-in. The slug exists because the shut-in "
        "allowed accumulation; the tail exists because release is diffusion-controlled "
        "and cannot be interrupted at flowback. A model that attributes the entire BTC "
        "to a single process therefore omits one of the two mechanisms that are "
        "demonstrably present in the experiment. The model developed below treats the "
        "BTC as the superposition of both sources, weighted by a smooth transition "
        "between them."
    ))

    # --- 2.2 Governing Equations -------------------------------------------
    anchor_22 = paras[i_23]  # heading 2.3
    write_into(paras[i_22 + 1], (
        "Tracer transport through the production tubing is governed by the "
        "one-dimensional advection–dispersion equation (ADE):"
    ))
    insert_before(anchor_22, "∂C/∂t + v·∂C/∂x = D·∂²C/∂x²", center=True)
    insert_before(anchor_22, (
        "where C is the tracer concentration, v is the cross-section-averaged flow "
        "velocity, and D is the longitudinal dispersion coefficient. For tube flow, the "
        "velocity is fixed by the volumetric flow rate Q and the tubing inner diameter "
        "d, and the dispersion coefficient is proportional to the velocity through the "
        "longitudinal dispersivity α:"
    ))
    insert_before(anchor_22, "v = 4Q/(πd²),  D = α·v", center=True)
    insert_before(anchor_22, (
        "The geometry is fixed by the experiment: x = 100 mm is the tubing length "
        "between the pack outlet and the sampling point, and d = 5 mm is the tubing "
        "inner diameter. Neither is fitted. Q and α are free parameters to be "
        "estimated from the BTC. For an instantaneous pulse of mass M released at "
        "x = 0 and t = 0, the ADE admits the classical solution "
        "C(x, t) = (M/A)·(1/√(4πDt))·exp(−(x − vt)²/(4Dt)), in which the "
        "concentration depends on x, v, D, and t only through the dimensionless "
        "similarity variable (x − vt)/√(4Dt) — the signed distance from the "
        "concentration peak normalized by the dispersion width. Substituting the "
        "tube-flow relations for v and D and clearing the fractional form in πd² "
        "yields the working dimensionless variable z:"
    ))
    insert_before(anchor_22, "z = (xπd² − 4Qt) / √(16αQtπd²)", center=True)
    insert_before(anchor_22, (
        "Here z = 0 marks the convective front, i.e., the concentration peak; z > 0 "
        "lies in the post-peak decay regime and z < 0 on the rising limb. The numerator "
        "is the spatial offset of the sampling point from the moving peak, and the "
        "denominator is the dispersion width, which grows as √t. In the fitted form, "
        "consistent units of mm, mL, and min are used throughout, so z is dimensionless."
    ))
    insert_before(anchor_22, (
        "The two tracer sources of Section 2.1 enter as two additive components. "
        "Source I, the shut-in accumulation slug, takes the instantaneous-pulse "
        "solution expressed in z:"
    ))
    insert_before(anchor_22, "C_rise(t) = c_b + (A·d)/√(16παQt·d²) × exp(−z²)", center=True)
    insert_before(anchor_22, (
        "where c_b is the baseline concentration (the asymptotic plateau of the BTC) "
        "and A is the pulse amplitude coefficient, proportional to the tracer mass that "
        "accumulated during shut-in. Source II, the sustained matrix-diffusion-"
        "controlled release, takes the erfc form appropriate to a source that is "
        "maintained over time:"
    ))
    insert_before(anchor_22, "C_fall(t) = c_b + (a/2) × erfc(−z)", center=True)
    insert_before(anchor_22, (
        "where a is the tail amplitude coefficient, the sustained-release source "
        "strength. The erfc component decays slowly and is the long-time signature of "
        "the non-exhausting polymer-matrix source, consistent with the non-Fickian "
        "release kinetics measured independently in batch experiments (Section 3.3). "
        "The two components are combined through a hyperbolic-tangent weight function:"
    ))
    insert_before(anchor_22, "w(t) = ½[1 + tanh((t₀ − t)/σ)]", center=True)
    insert_before(anchor_22, (
        "C(t) = c_b + w(t)·C_rise(t) + [1 − w(t)]·C_fall(t)   (Eq. 1)"
    ), center=True)
    insert_before(anchor_22, (
        "The crossover time t₀ locates the transition from slug-dominated to "
        "tail-dominated behavior, and the transition width σ controls its sharpness. "
        "σ is fitted — its value (3.96 min, Section 4.2) is approximately the 4-min "
        "sampling interval, providing a physically motivated regularization — whereas x "
        "and d remain fixed geometry. As t ≪ t₀, w → 1 and C(t) → C_rise(t); "
        "as t ≫ t₀, w → 0 and C(t) → C_fall(t); near t₀ the two signals mix "
        "smoothly over a window of width ≈ 8–10 min. Because both components and w are "
        "smooth, the blended curve (Eq. 1) is C¹-continuous, a requirement for "
        "gradient-based optimization: a hard piecewise switch at t₀ would introduce a "
        "non-differentiable kink at the crossover, and no physical mechanism switches "
        "the two release processes instantaneously."
    ))

    # --- 2.3 Parameter Set and Derived Quantities --------------------------
    anchor_23 = paras[i_24]  # heading 2.4
    write_into(paras[i_23 + 1], (
        "Equation (1) contains seven parameters — c_b, A, a, α, Q, t₀, and σ — "
        "whose physical meanings and model origins are summarized in Table 1. Three "
        "derived transport quantities are computed from the fitted values: the Peclet "
        "number Pe = x/α, which measures the balance of advection to dispersion; the "
        "mean flow velocity v = 4Q/(πd²); and the mean residence time MRT = x/v."
    ))
    caption = anchor_23.insert_paragraph_before()
    r_cap = caption.add_run("Table 1.  ")
    r_cap.bold = True
    caption.add_run("Parameter set of the coupled release–transport model (Eq. 1).")

    rows = [
        ("Parameter", "Symbol", "Origin", "Physical meaning"),
        ("Baseline concentration", "c_b", "Both", "Asymptotic plateau of the BTC"),
        ("Pulse amplitude", "A", "Rise", "Tracer mass accumulated during shut-in"),
        ("Tail amplitude", "a", "Fall", "Sustained-release source strength"),
        ("Longitudinal dispersivity", "α", "Rise", "Dispersion in the production tubing"),
        ("Flow rate", "Q", "Rise", "Target parameter — unconstrained in the fit"),
        ("Crossover time", "t₀", "Both", "Slug-to-tail transition time"),
        ("Transition width", "σ", "Both", "Fitted, ≈ sampling interval"),
    ]
    tbl = doc.add_table(rows=len(rows), cols=len(rows[0]))
    try:
        tbl.style = "Table Grid"
    except Exception:
        pass
    for i, row in enumerate(rows):
        for j, val in enumerate(row):
            cell = tbl.cell(i, j)
            p = cell.paragraphs[0]
            add_runs(p, val, bold=(i == 0))
    caption._p.addnext(tbl._tbl)  # move table from doc end to after caption

    insert_before(anchor_23, (
        "Two parameters require explicit comment. σ is nominally free but is fitted "
        "with a physically motivated scale: its value is close to the 4-min sampling "
        "interval, and Section 4.5 shows that the conclusions are insensitive to σ "
        "over a six-fold range. Q is the target parameter of this study: it receives no "
        "penalty, prior, or constraint toward any particular value in the objective "
        "function. Q is bounded only by the search envelope [10, 5000] mL/min "
        "(Table S6) — a 500-fold range — which admits every flow rate physically "
        "possible in the apparatus while exercising no bias on the outcome. If the "
        "model structure is correct, Q must emerge from the concentration data alone; "
        "Section 2.4 formalizes this requirement as the validation test."
    ))

    # --- 2.4 Validation Strategy -------------------------------------------
    anchor_24 = paras[i_3]  # heading 3. Experimental Methods
    write_into(paras[i_24 + 1], (
        "Goodness-of-fit statistics alone cannot validate a model of this class. R² "
        "and RMSE measure how well a curve of k parameters reproduces 21 data points; "
        "they cannot distinguish a physically correct model from an overfitted one with "
        "the same number of parameters. Every single-process alternative considered in "
        "Section 4.1 achieves a respectable fit to part of the BTC. The question is "
        "therefore not whether Eq. (1) fits the data, but whether its parameters are "
        "physically real."
    ))
    insert_before(anchor_24, (
        "The validation strategy adopted here is predictive rather than descriptive. Q "
        "is a physical quantity with an independent, known value: the pump was set to "
        "0.50 mL/min during the displacement experiment (Section 3.4). The model is "
        "given no access to this value — Q enters the objective function without "
        "penalty, prior, or constraint toward the pump setting, bounded only by the "
        "[10, 5000] mL/min search envelope (Section 2.3). If the model structure were "
        "incorrect, the optimizer would assign Q an arbitrary value within that "
        "envelope, compensating with A and α to preserve the fit; the fitted Q would "
        "then be a curve-matching artifact. If the model structure is correct, Q must "
        "converge to approximately the pump value, because that is the only flow rate "
        "consistent with the timing and shape of the observed BTC."
    ))
    insert_before(anchor_24, (
        "The test is falsifiable. If Q converged to 2.3 or 0.07 mL/min while R² "
        "remained at 0.99, the model would be wrong regardless of its statistical "
        "performance: its fitted Q would contradict an independently measured physical "
        "quantity. A converged value of Q consistent with the pump setting across "
        "independent searches therefore constitutes positive evidence — a successful "
        "prediction — that the model structure captures the transport physics rather "
        "than the curve shape. Section 4.2 reports the outcome of this test."
    ))

    doc.save(DOCX)
    print("saved:", DOCX)
    return i_h1


def verify():
    """Re-open the document and cross-check Section 2 against the spec."""
    doc = Document(DOCX)
    paras = doc.paragraphs
    full = "\n".join(p.text for p in paras)

    # Locate Section 2 extent
    idx = [p.text.strip() for p in paras]
    start = idx.index("2. Coupled Release–Transport Model")
    end = idx.index("3. Experimental Methods")
    sec = "\n".join(paras[i].text for i in range(start, end))

    checks = {
        "ADE equation": "∂C/∂t + v·∂C/∂x = D·∂²C/∂x²" in full,
        "tube-flow substitution": "v = 4Q/(πd²),  D = α·v" in full,
        "z variable": "z = (xπd² − 4Qt) / √(16αQtπd²)" in full,
        "C_rise component": "Crise(t) = cb + (A·d)/√(16παQt·d²) × exp(−z²)" in full,
        "C_fall component": "Cfall(t) = cb + (a/2) × erfc(−z)" in full,
        "tanh weight": "w(t) = ½[1 + tanh((t₀ − t)/σ)]" in full,
        "full model Eq. 1": "C(t) = cb + w(t)·Crise(t) + [1 − w(t)]·Cfall(t)   (Eq. 1)" in full,
        "fixed x = 100 mm": "x = 100 mm" in sec,
        "fixed d = 5 mm": "d = 5 mm" in sec,
        "Q bounds [10,5000]": "[10, 5000] mL/min" in sec,
        "500-fold range": "500-fold" in sec,
        "pump 0.50 mL/min": "0.50 mL/min" in sec,
        "Q unconstrained": "no penalty, prior, or constraint" in sec,
        "C1 continuity": "C¹-continuous" in sec,
        "Pe = x/alpha": "Pe = x/α" in sec,
        "MRT = x/v": "MRT = x/v" in sec,
        "Fig. 1 marker intact": "[Fig. 1 placeholder" in full,
    }
    ok = True
    for name, passed in checks.items():
        print(f"  [{'OK' if passed else 'FAIL'}] {name}")
        ok = ok and passed

    # Word counts per subsection
    heads = {
        "2.1 Physical Basis": None,
        "2.2 Governing Equations": None,
        "2.3 Parameter Set and Derived Quantities": None,
        "2.4 Validation Strategy: Self-Calibration as Decisive Test": None,
    }
    pos = {}
    for i in range(start, end):
        t = paras[i].text.strip()
        if t in heads:
            pos[t] = i
    order = list(pos.keys())
    for j, h in enumerate(order):
        lo = pos[h] + 1
        hi = pos[order[j + 1]] if j + 1 < len(order) else end
        words = sum(len(paras[k].text.split()) for k in range(lo, hi))
        print(f"  words in {h}: {words}")

    lead_words = len(paras[start + 1].text.split())
    print(f"  words in section lead-in: {lead_words}")

    # Table check
    n_tables = len(doc.tables)
    t1 = doc.tables[0] if n_tables else None
    print(f"  tables in document: {n_tables}")
    if t1 is not None:
        print(f"  Table 1 dims: {len(t1.rows)} rows x {len(t1.columns)} cols")
        header = [c.text for c in t1.rows[0].cells]
        print(f"  Table 1 header: {header}")
        ok = ok and len(t1.rows) == 8 and len(t1.columns) == 4 and header == [
            "Parameter", "Symbol", "Origin", "Physical meaning"]

    # Caption and table placement checks
    caption_ok = "Table 1.  Parameter set of the coupled release–transport model (Eq. 1)." in full
    print(f"  [{'OK' if caption_ok else 'FAIL'}] Table 1 caption text")
    ok = ok and caption_ok

    # Display equations must be centered
    eq_texts = [
        "∂C/∂t + v·∂C/∂x = D·∂²C/∂x²",
        "v = 4Q/(πd²),  D = α·v",
        "z = (xπd² − 4Qt) / √(16αQtπd²)",
        "Crise(t) = cb + (A·d)/√(16παQt·d²) × exp(−z²)",
        "Cfall(t) = cb + (a/2) × erfc(−z)",
        "w(t) = ½[1 + tanh((t₀ − t)/σ)]",
        "C(t) = cb + w(t)·Crise(t) + [1 − w(t)]·Cfall(t)   (Eq. 1)",
    ]
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    for eq in eq_texts:
        for p in paras:
            if p.text.strip() == eq:
                centered = p.alignment == WD_ALIGN_PARAGRAPH.CENTER
                print(f"  [{'OK' if centered else 'FAIL'}] centered: {eq[:45]}...")
                ok = ok and centered
                break
        else:
            print(f"  [FAIL] missing equation: {eq[:45]}...")
            ok = False

    print("VERIFICATION", "PASSED" if ok else "FAILED")
    return ok


if __name__ == "__main__":
    main()
    ok = verify()
    sys.exit(0 if ok else 1)
